title: Grading System Project
description: Using PHP, HTML, CSS and JavaScript this project was meant for the teachers to insert their student's grades in a phpMyAdmin database
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
